### ISSUE TITLE
Can we load images from relative path?

### ISSUE THREAD

**Issue by kelumkps** [relevantcodes/extentreports#1]
This is the great library to generate test reports. Thank you for a wonderful job. I have one suggestion to make.
Currently html tag for images loads the source images using "fill:///" protocol. (i.e "file:///" is prefixed to the image path of src)
As I noticed, we need to pass full absolute path of the image to load it correctly on report. When we pass a relative path images are not loaded from the report.
Passing relative path is very helpful when we want to share the report with others. So it is great if you can enable this capability.

**Comment by relevantcodes** [comment]
Kelum,  this will be fully supported on v1.2.

Can you try your code with v1.2-alpha and let me know if it works?

http://relevantcodes.com/Tools/ExtentReports/extentreports-java-1.2a.jar.zip

**Comment by kelumkps** [comment]
Hello Anshoo,

Thanks for the quick response. I tried to run my project with the given .jar file (extentreports-java-1.2a.jar). However, I'm getting a NullPointerException when calling init() method of ExtentReports. Below is the stack trace for your review.

java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at java.util.Scanner.<init>(Scanner.java:563)
	at com.relevantcodes.extentreports.support.Stream.toString(Stream.java:27)
	at com.relevantcodes.extentreports.support.Resources.getText(Resources.java:26)
	at com.relevantcodes.extentreports.Logger.writeBaseMarkup(Logger.java:116)
	at com.relevantcodes.extentreports.Logger.<init>(Logger.java:128)
	at com.relevantcodes.extentreports.ExtentReports.init(ExtentReports.java:94)
	at ExtentReportsDemo.main(ExtentReportsDemo.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
java.lang.NullPointerException
	at com.relevantcodes.extentreports.support.RegexMatcher.getNthMatch(RegexMatcher.java:37)
	at com.relevantcodes.extentreports.markup.Content.renewSystemInfo(Content.java:52)
	at com.relevantcodes.extentreports.markup.DocumentConfig.renewSystemInfo(DocumentConfig.java:107)
	at com.relevantcodes.extentreports.ExtentReports.initialProc(ExtentReports.java:103)
	at com.relevantcodes.extentreports.ExtentReports.init(ExtentReports.java:96)
	at ExtentReportsDemo.main(ExtentReportsDemo.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Exception in thread "main" java.lang.NullPointerException
	at java.lang.String.replace(String.java:2227)
	at com.relevantcodes.extentreports.markup.Content.renewSystemInfo(Content.java:53)
	at com.relevantcodes.extentreports.markup.DocumentConfig.renewSystemInfo(DocumentConfig.java:107)
	at com.relevantcodes.extentreports.ExtentReports.initialProc(ExtentReports.java:103)
	at com.relevantcodes.extentreports.ExtentReports.init(ExtentReports.java:96)
	at ExtentReportsDemo.main(ExtentReportsDemo.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Thanks
-Kelum

**Comment by relevantcodes** [comment]
Can you share the init() call that generated this error? Is the file in a location that locks it, for example, is it part of your project?

**Comment by kelumkps** [comment]
This is the code snippet which calls init() method. The "reportLocation" directory is available. I didn't create any file in this directory. ScreenshotReport.html file is generated when program is running bt the ExtentReports library. When I open this file I could see string "null" was written to the it.

public class ExtentReportsDemo {
 
    static final ExtentReports extent = ExtentReports.get(ExtentReportsDemo.class);
    static WebDriver driver = new FirefoxDriver();
 
    static String reportLocation = "C:\\Users\\ksenanayake\\Desktop\\myprojc\\report\\";
    static String imageLocation = "images/";
     
    public static void main (String args[]) {
        extent.init(reportLocation + "ScreenshotReport.html", true, DisplayOrder.BY_OLDEST_TO_LATEST);
        extent.config().reportHeadline("Test report for ParaBank login tests generated using <b>ExtentReports</b>");
        extent.startTest("TC01.1","This test is a positive login test for ParaBank");
        runPositiveTest();
        extent.endTest();
 
        extent.startTest("TC01.2","This is a negative login test for ParaBank (contains a defect)");
        runNegativeTest();
        extent.endTest();
 
        driver.quit();
    }


Note : I'm using the same source code available on here and Java 8 to compile & run. 
http://www.ontestautomation.com/creating-html-reports-for-your-selenium-tests-using-extentreports/

**Comment by relevantcodes** [comment]
I received the same issue when I ran on another machine.  Checked and found that my project had become corrupt.  Can you please try with the same link again?  I have uploaded the fixed build.

http://relevantcodes.com/Tools/ExtentReports/extentreports-java-1.2a.jar.zip

**Comment by kelumkps** [comment]
I tried with the new library. Now it runs without any error. However, still "fill:///" is prefixed with image path. Therefore, when I pass a relative path, screen shots are not loaded in browser.

HTML image tag when relative path is provided. This doesn't load the screen shot.
```html
<img class="report-img" data-featherlight="file:///images/eb5cfcfe-037f-4856-bc02-d5dcea5b3a09.png" src="file:///images/eb5cfcfe-037f-4856-bc02-d5dcea5b3a09.png" height="50px" width="100px">
```
HTML image tag when absolute path is provided. This loads the screen shot correctly.
```html
<img class="report-img" data-featherlight="file:///C:/Users/ksenanayake/Desktop/myprojc/report/images/99d80a30-893a-448f-9b9c-d1d7e34a465c.png" src="file:///C:/Users/ksenanayake/Desktop/myprojc/report/images/99d80a30-893a-448f-9b9c-d1d7e34a465c.png" height="50px" width="100px">
```

**Comment by relevantcodes** [comment]
Kelum

I see. I can completely remove file:/// to be added to the path string which will allow for all relative paths type. Issues may arise for users who use absolute path if they fail to remember to append file:/// though.

Relative paths starting with a "." and "/" work fine but the one you mentioned is quite tricky to handle without breaking normal behavior.

I am thinking removal of it. Creating a small how-to guide sounds like a better idea.  It will then work for all types of relative paths and for absolute ones, file:/// can be appended manually.

Thank you.

**Comment by kelumkps** [comment]
Hello Anshoo,
As you said, I tried with "./" to specify relative path (ex: "./images/screen-1.png"). Then images are loaded properly. This is good enough for me. Many thanks for the support regarding this feature.
